---
# centos.yml tasks file for ansible-role-pass
#
# Migrate to epel role at a later date?

- name: Ensure that all centOS systems have the latest security updates installed
  yum:
    name     : '*'
    security : yes # option only available in ansible 2.4 and greater.
    state    : latest
  become: yes
  when: ansible_distribution == "CentOS"
        && "{{ ansible_version is defined }}"
        && "{{ ansible_version|version_compare(2.4.0 '>=') }}"

- name: Ensure centOS systems are updated to the latest packages
  yum:
    name : '*'
    state: latest
  become: yes
  when: ansible_distribution == "CentOS"

- name: Ensure that centOS system get EPEL
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    gpgkey: https://download.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
    gpgcheck: yes
  become: yes
  when: ansible_distribution == "CentOS"

